name: Ding Gesellschaft
favicon: null
layout_spectrum: 0.3507862917613238
typography_spectrum: 0.8558172062039375
title: Ding Gesellschaft
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#4cb421'
    - '#b7b7b7'
    - '#5d5d5d'
  brandStrength: 0.8125
  lightness: 0.7400909825228155
  saturation: 0.7435632008127868
  rhythmicContrast: 1
purpose: []
