name: Ding Gesellschaft
favicon: null
layout_spectrum: 0.14254
typography_spectrum: 0.15128
title: Ding Gesellschaft
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#181818'
    - '#a0b475'
    - '#ae4544'
    - '#f9c991'
    - '#585858'
  brandStrength: 0.8125
  lightness: 0.7400909825228155
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
